# Uygulaman?n çal??aca?? port ayar?
server.port=8585

# Özel tan?mlamalar (Custom Properties)
course.name=Workintech Java Spring Boot
project.developer.fullname=Ceyhan Fazlioglu

# Spring DevTools otomatik restart aktif etme (Zaten dependency ekliyse otomatik çal???r)
spring.devtools.restart.enabled=true